config/routes.rb
Rails.application.routes.draw do

  resources :topics, only: [:index, :show]
  
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  
  get 'angular-items', to: 'portfolios#angular'
  get 'portfolio/:id', to: 'portfolios#show', as:'portfolio_show'

  get 'about', to: 'pages#about'

  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'


  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'
end

app/views/shared/_application_footer.html.erb
<div class="mastfoot">
  <div class="inner">
    <p><%= @copyright %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="masthead clearfix">
  <div class="inner">
    <h3 class="masthead-brand">Ryan Andersen</h3>
    <nav class="nav nav-masthead app-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= @copyright %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="blog-header">
  <div class="container">
    <h1 class="blog-title">My Blog</h1>
    <p class="lead blog-description">This is a live blog where site admins can create and publish blogs. All users are allowed to comment on any blog.</p>
    <span>
      <%= link_to 'Write a New Blog', new_blog_path if logged_in?(:site_admin) %>
    </span>
    
    <span>
      <%= link_to "Topics", topics_path %>
    </span>
  </div>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
    <div class="container">
        <nav class="nav blog-nav">
           <%= nav_helper 'nav-link', 'span' %>
           <%= login_helper 'nav-link' %>
        </nav>
    </div>
</div>









    

app/views/shared/_blog_sidebar.html.erb
 <div class="col-sm-3 offset-sm-1 blog-sidebar">
  <div class="sidebar-module sidebar-module-inset">
    <h4>About</h4>
    <p>I probably won't post much here, this is really just showing what this site can do. Look below to see where else you find me, or visit the <%= link_to 'contact me', contact_path %> page.</p>
  </div>
  
   <%= source_helper("alert alert-info blog-sidebar-source") %>
  
  <div class="sidebar-module">
    <h4>Topics</h4>
   
   
    <% @side_bar_topics.each do |topic| %>
      <p><%= link_to topic.title, topic_path(topic) %></p>
      <% end %>
      <p><%= side_top("Computer Science/Programming", 1)%></p>
      <p><%= side_top("Thoughts", 2)%></p>

  </div>
  
  <div class="sidebar-module">
    <h4>Elsewhere</h4>
    <ol class="list-unstyled social-links" >
      <li><a href="https://github.com/WizardRyan"><%= fa_icon "github" %></a></li>
      <li><a href="https://plus.google.com/+RyanAndersen117"><%= fa_icon "google-plus" %></a></li>
      <li><a href="http://steamcommunity.com/profiles/76561198274518846/"><%= fa_icon "steam" %></a></li>
     <!-- <li><a href="#"><%#= fa_icon "linkedin" %></a></li> -->
    </ol>
  </div>

app/views/shared/_nav.html.erb
  <div class="<%= location %>">
         <div> <%= link_to 'Home', root_path %></div>
         <div> <%= link_to 'About', about_path %></div>
         <div> <%= link_to 'Contact', contact_path %></div>
         <div> <%= link_to 'Blog', blogs_path %></div>
         <div> <%= link_to 'Portfolio', portfolios_path %></div>
       </div>

app/views/shared/_portfolio_footer.html.erb
 <footer class="text-muted">
  <div class="container">
    <p class="float-right">
      <%= link_to "Back to all Portfolio Items", portfolios_path %> | 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= @copyright %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">My Portfolio</h1>
    <p class="lead text-muted">Below is where I'll be putting projects I've worked on. Right now, a lot of them are going to be empty, and are filled with sample data I generated. I'll just leave 'em there because I think it looks nice.</p>
    <p>
      <%= link_to 'Find Out More About Me', about_path, class: 'btn btn-outline-secondary btn-block' %>
    </p>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<div class="collapse bg-inverse navbar-custom" id="navbarHeader">
  <div class="container">
    <div class="row">
      <div class="col-sm-8 py-4">
        <h4 class="text-white">About</h4>
        <p class="text-muted">Below is where I'll be putting projects I've worked on, feel free to check out the rest of my site. Or, you can enjoy reading the rest of this text that I'm putting in because it's more aesthetically pleasing. Oh boy golly gee, is this going to be the right amount of text? Maybe a little more, like another sentence or two. Yup, this looks good.</p>
      </div>
      <div class="col-sm-4 py-4">
        <h4 class="text-white">Explore</h4>
        <ul class="list-unstyled">
          <%= nav_helper 'text-white', 'li' %>

          <li><%= login_helper 'text-white' %></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="navbar navbar-inverse bg-inverse navbar-custom">
  <div class="container d-flex justify-content-between">
    <a href="#" class="navbar-brand">Ryan Andersen</a>
    <button class="navbar-toggler btn btn-secondary" type="button" data-toggle="collapse" data-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
      <span class="nav-bars"><strong>≡</strong></span>
    </button>
  </div>
</div>